version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: climate-data-example-python
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]
    environment:
      - PYTHONUNBUFFERED=1